---
title: "Alumnae"
---

## Doctoral Students

### University of Florida: 2002-2006

1. Samiran Sinha, (Ph.D. 2004; Co-chair with Malay Ghosh) Professor, Department of Statistics, Texas A & M University.

https://scholars.library.tamu.edu/vivo/display/nf7f32f6f/Persons/View%20All

2. Li Zhang, (Ph.D. 2006; Co-chair with Malay Ghosh) Professor, Division of Hematology and
Medical Oncology Department of Medicine UCSF Helen Diller Family Comprehensive Cancer
Center and Department of Epidemiology and Biostatistics University of California, San
Francisco.

https://profiles.ucsf.edu/li.zhang

3. Upasana Santra, (Ph.D. 2007; Co-chair with Malay Ghosh), Lecturer, Valencia Community
College, Florida. 

https://frontdoor.valenciacollege.edu/faculty.cfm?uid=usantra

### University of Michigan: 2006-

1. Jaeil Ahn, (Ph.D. 2011; Co-chair with Timothy Johnson), Associate Professor, Georgetown
University, Division of Biostatistics and Bioinformatics.

https://gufaculty360.georgetown.edu/s/contact/00336000014TT9nAAG/jaeil-ahn

2. Philip Simon Boonstra, (Ph.D. 2012; (Co-chair with Jeremy MG Taylor). Associate
 Professor, Department of Biostatistics, University of Michigan.
 
 https://public.websites.umich.edu/~philb/education.html
 
3. Shi Li, (Ph.D. 2013) Statistician at Genentech, California.

https://www.linkedin.com/in/shi-li-1847bb50/

4. Yi-An Ko, (Ph.D. 2014), Research Associate Professor, Department of Biostatistics, Emory
University.

https://sph.emory.edu/faculty/profile/index.php?FID=yi-an-ko-8701


5.	Zhichao Sun, (Ph.D. 2016; Co-chair with Thomas Braun). Senior Biostatistician at Boehringer Ingelheim Pharmaceuticals, Connecticut.

https://www.linkedin.com/in/zhichao-sun-ab9a3690/

6.	Zihuai He, (Ph.D. 2016; Co-chair with Min Zhang). Research Assistant Professor, Neurology & Neurological Sciences, Research Assistant Professor, Medicine - Biomedical Informatics Research, Stanford University.

https://profiles.stanford.edu/zihuai-he

7.	Yin-Hsiu Chen, (Ph.D, 2017). Quantitative/Data Analyst, Google Inc, California.

https://www.linkedin.com/in/yin-hsiu-aaron-chen-36a15129/


8.	Wenting Cheng, (Ph.D, 2017; Co-chair with Jeremy MG Taylor). Statistician, Biogen Inc, Boston, Massachusetts.

https://www.linkedin.com/in/wenting-cheng-57873224/

9.	Yanyi Song, (Ph.D, 2020; Co-chair with Xiang Zhou). Data Scientist at Facebook/Meta.

https://www.linkedin.com/in/yanyi-song-555b087b/

10.	Zhongsheng Chen, (Ph.D 2020; Co-chair with Michael L Boehnke). Senior Biostatistician II, Vertex, Boston, Massachusetts.

11.	Zhangchen Zhao, (Ph.D, 2021; Co-chair with Shawn Lee). Statistician, Eli Lilly & Co.

https://www.linkedin.com/in/zhangchen-zhao-a93a4885/

12.	Tian Gu, (Ph.D., 2021; Co-chair with Jeremy MG Taylor). Assistant Professor in Biostatistics, Columbia University, Mailman School of Public Health.

https://www.publichealth.columbia.edu/profile/tian-gu-phd

13.	Youfei Yu, (Ph.D., 2021; Co-chair with Min Zhang). Biostatistics Manager, Amgen Inc.

https://www.linkedin.com/in/youfei-yu-a6ba9b3b/

14.	Yongwen Zhuang, (Ph.D, 2022; Co-chair with Shawn Lee). Biostatistician, Illumina Inc.

https://www.linkedin.com/in/yongwen-zhuang/

15.	Jonathan Boss, (Ph.D, 2023; Co-chair with Jian Kang). Biostatistician, Eli Lilly & Co.

https://www.linkedin.com/in/jonathan-boss-75768377/

16.	Maxwell Salvatore, (Ph.D, 2024; Co-chair with Leigh Pearce). Post-doctoral fellow, Division of Biostatistics, Epidemiology, and Informatics, University of Pennsylvania School of Medicine.

https://ritchielab.org/people/post-doctral-fellow/max-salvatore



## Post Doctoral Fellows

### University of Michigan: 2006-

1. Jason P Estes (PhD in Biostatistics, UCLA), 2016-2017. Statistician at Google Inc.

https://www.linkedin.com/in/jason-estes-phd-2b0408113/

2. Lauren Beesley (PhD in Biostatistics, University of Michigan), 2018-2021. Feynman Distinguished
Postdoctoral Fellow (2021-2023); Staff Scientist/Statistician (2023-) Analytics, Intelligence and
Technology Division: Information Systems and Modeling, Los Alamos National Laboratory.

https://lbeesleybiostat.wordpress.com/


3. Max Aung (PhD in Environmental Health Sciences, University of Michigan), 2019-2020. Assistant
Professor, University of Southern California, KECC School of Medicine.

https://keck.usc.edu/faculty-search/max-m-aung/


 