---
title: "Education and Outreach"
editor: visual
filters:
  - newpagelink.lua
---

# [Transforming Analytical Learning in the Era of Big Data: A Summer Institute in Biostatistics (SIBS) Program](https://sph.umich.edu/bdsi/)

Adding a line.

The Big Data Summer Institute, a SIBS program, is an interdisciplinary training and research program in biostatistics that introduces undergraduate students to the intersection of big data and human health — a rapidly growing field that uses quantitative analysis to help solve scientific problems and improve people’s lives.

Drawing from the expertise and experience of outstanding faculty of several departments at the University of Michigan — biostatistics, statistics, and electrical engineering and computer science — the institute exposes undergraduate students to diverse experiences and techniques that distinguishes it from any other undergraduate summer program in biostatistics in the country.

This Summer Institute in Biostatistics (SIBS) program is sponsored by the National Heart, Lung, and Blood Institute (NHLBI), grant R25HL147207, with the intent to introduce undergrad students to the field of biostatistics. Courses will include data collected in studies of heart, lung, blood, and sleep disorders. To learn more about our sister programs, please visit the NHLBI SIBS program website.      
