---
title: "People"
---

Bhramar Mukherjee, PhD

<Headshot comes here>

Senior Associate Dean of Public Health Data Science and Data Equity; Anna M.R Lauder Professor of Biostatistics; Professor of Epidemiology (Chronic Diseases) and of Statistics and Data Science


Alicia E. Boyd, PhD

<Headshot comes here>

Alicia Boyd, PhD, is an associate research scientist in the Department of Biostatistics at Yale School of Public Health. She received her PhD in Computer Science from DePaul University in Chicago, Illinois, and completed her postdoctoral fellowship at New York University. She is an affiliate researcher with the Interdisciplinary Software Practice Improvement Research and Development (or INSPIRED) Lab at George Mason University and Gadiraju Lab at Wellesley College.  

 

Dr. Boyd is a social-technical researcher guided by wisdom, patience, and thoughtfulness. Her research is at the intersection of technology, privacy, and reflexivity, which aims to implement reflexive practices in quantitative areas such as software development, large language models, data science, and machine learning. Some of her recent and ongoing projects include the investigation of improving disability representation in generative artificial intelligence models and how to incorporate reflexive practices in gig work design. Within the Data Science Data Equity (DSDE) Initiative, Dr. Boyd hopes to develop a reflexive praxis for technical applications. 


Howard Baek, M.S.

<Headshot comes here>

Howard Baek is a Data Scientist with a background in biostatistics and computer science. He holds a Master of Science in Biostatistics, and a Bachelor of Science in Statistics with a minor in Mathematics, both from the University of Washington. He is working towards a Post-Baccalaureate Degree in Computer Science from Oregon State University. 

Currently, he is a Data Scientist I at Yale University, where he develops and executes statistical models for analyzing EHR and biobank datasets, and creates software packages to enhance data analysis and accessibility.  